export const START_PLAYING_AUDIO_TRACK = 'start_playing_audio_track'
export const START_PLAYING_NEXT_AUDIO_TRACK_FRAGMENT = 'start_playing_next_audio_track_fragment'
export const PAUSE_PLAYING_AUDIO_TRACK = 'pause_playing_audio_track'
export const RESUME_PLAYING_AUDIO_TRACK = 'resume_playing_audio_track'
export const STOP_PLAYING_AUDIO_TRACK = 'stop_playing_audio_track'
export const FINISH_PLAYING_AUDIO_TRACK = 'finish_playing_audio_track'
export const RELEASE_PLAYED_AUDIO_TRACK = 'release_played_audio_track'
